# Generated by Django 5.0.2 on 2024-04-01 21:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_foto_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('texto', models.CharField(max_length=900)),
                ('like_count', models.BigIntegerField(default=0)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_postou', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
