# Generated by Django 5.0.2 on 2024-04-01 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likado', to='api.posts')),
                ('quem_deu_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
